<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CATEGORIES_card-img-top img-fluid</name>
   <tag></tag>
   <elementGuidId>da29d42e-0376-4b17-b7b0-7222e437a8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbodyid']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87d59d39-db92-4981-af1b-a4f419ca1faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top img-fluid</value>
      <webElementGuid>1832e244-4d8a-43e4-b95e-3a9abd7dbcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>imgs/galaxy_s6.jpg</value>
      <webElementGuid>11d38e7a-2809-4e4a-b919-1c7426dafe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbodyid&quot;)/div[@class=&quot;col-lg-4 col-md-6 mb-4&quot;]/div[@class=&quot;card h-100&quot;]/a[1]/img[@class=&quot;card-img-top img-fluid&quot;]</value>
      <webElementGuid>9e9fd824-770a-47b5-abd8-93a4b11a2121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbodyid']/div/div/a/img</value>
      <webElementGuid>f4ba69ea-cc35-4453-a023-60bf3163987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>c305c9c3-214f-4ae7-813b-94189589f44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'imgs/galaxy_s6.jpg']</value>
      <webElementGuid>cccba286-14a9-4004-b5c0-f98d74e6d2fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
